"""fix_user_schema_mismatches

Revision ID: 3f5925fb172a
Revises: 8e4f2a9b1c6d
Create Date: 2025-08-31 12:43:28.097035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5925fb172a'
down_revision = '8e4f2a9b1c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_assigned_to_users', 'tasks', type_='foreignkey')
    
    # Alter column types
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    
    # Add new columns and index
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Recreate foreign key constraints with correct types
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_tasks_assigned_to_users', 'tasks', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    op.drop_constraint('fk_tasks_assigned_to_users', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    
    # Reverse column drops
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    
    # Reverse column type changes
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    
    # Recreate original foreign key constraints
    op.create_foreign_key('fk_tasks_assigned_to_users', 'tasks', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
